server:
  port: 16062

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,refresh,bus-refresh

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 10000
      idleTimeout: 10000
      maximumPoolSize: 10
      minimumIdle: 5
      validation-timeout: 10000
    password: qwer1234
    url: jdbc:mariadb://192.168.56.151:33306/productdb
    username: product
  rabbitmq:
    host: localhost
    password: qwer1234
    port: 5672
    username: jpetstore
